JPEGView/ImageLoadThread.cpp
WEBP/WEBP.cpp

Adds transparency support for the WEBP format. Honours the "TransparencyColor" INI setting. Partially addresses issue #13 and closes issue #6.

WebP background transparency color support

---

src/JPEGView/ImageLoadThread.cpp

Checks if a file is a PNG, GIF, or TIFF image using the magic bytes in the header before falling back to checking the file extension. This fixes https://github.com/sylikc/jpegview/issues/78.

Check magic bytes for more image formats

---

src/JPEGView/MainDlg.cpp

This fixes a bug where still images in a folder can unintentionally get played like an animation.
To reproduce:
- Open an animated GIF
- Drag and drop a still image from a folder with multiple images into JPEGView
JPEGView will then cycle through all images in the folder at the speed of the animation. To fix this, the animation must be stopped when opening a file.

Stop animation/slideshow when opening file

---

src/JPEGView/ImageLoadThread.cpp
src/JPEGView/JPEGImage.h

The behavior of JPEGView differs from the major web browsers when displaying animated images with frame durations <= 10.
Currently, JPEGView displays all 0ms GIF frames as 100ms, and all <10ms frames (for other formats) as 10ms. 
Most web browsers display all <=10ms frames as 100ms:
- [Mozilla](https://hg.mozilla.org/mozilla-central/file/tip/image/FrameTimeout.h#l54)
- [Blink](https://chromium.googlesource.com/chromium/blink/+/refs/heads/main/Source/platform/graphics/ImageSource.cpp#116)
- [WebKit](https://github.com/WebKit/WebKit/blob/main/Source/WebCore/platform/image-decoders/ScalableImageDecoder.cpp#L252-L259)
Some examples that display differently in JPEGView:
0-delay APNG
1-delay GIF (centiseconds)
Some relevant posts:
[The Fastest GIF Does Not …

Treat frame durations <= 10 ms as if they were 100 ms

---

src/JPEGView/ImageLoadThread.cpp

This restores ICC profile support for PNGs when UseEmbeddedColorProfiles=true, but disables animation. For example, the bench in this image currently displays as green in JPEGView when it should be red.

Use GDI+ to load PNGs when ForceGDIPlus or UseEmbeddedColorProfiles is true

---

src/JPEGView/AVIFWrapper.cpp
src/JPEGView/AVIFWrapper.h
src/JPEGView/EXIFDisplayCtl.cpp
src/JPEGView/EXIFReader.cpp
src/JPEGView/EXIFReader.h
src/JPEGView/HEIFWrapper.cpp
src/JPEGView/HEIFWrapper.h
src/JPEGView/ImageLoadThread.cpp
src/JPEGView/JPEGImage.cpp
src/JPEGView/JXLWrapper.cpp
src/JPEGView/JXLWrapper.h
src/JPEGView/PNGWrapper.cpp
src/JPEGView/PNGWrapper.h
src/JPEGView/SaveImage.cpp
src/JPEGView/WEBPWrapper.cpp
src/JPEGView/WEBPWrapper.h

Adds support for reading JPEG XL, HEIF, AVIF, WebP and PNG Exif data. ~~Doesn't work for animated JXLs~~. https://github.com/sylikc/jpegview/pull/213/commits/e1852b2879552465649535615531050aa65e6939 fixes a memory leak I introduced in https://github.com/sylikc/jpegview/pull/208 (my bad) and https://github.com/sylikc/jpegview/pull/213/commits/2ce3887476c5d5edae09731ac4916e8269e6b514 partially fixes https://github.com/sylikc/jpegview/issues/207.

JXL/HEIF/AVIF/WebP/PNG Exif data support

---

.github/actions/upload-some-artifacts/action.yml

Removes the debugging/linking files for WICLoader before uploading release artifacts

clean up WICLoader files before uploading artifacts

---

src/JPEGView/HEIFWrapper.cpp
src/JPEGView/JXLWrapper.cpp

Speed up RGBA -> BGRA conversion by ~25% for JXL and ~150% for HEIF.
Slow:  
`((value & 0x00FF0000) >> 16) | ((value & 0x000000FF) << 16) | (value & 0xFF00FF00);`  
Faster:  
`_rotr(value & 0x00FF00FF, 16) | (value & 0xFF00FF00);`  
`(((value >> 16) | (value << 16)) & 0x00FF00FF) | (value & 0xFF00FF00);`  
`((_byteswap_ulong(value) >> 8) & 0x00FF00FF) | (value & 0xFF00FF00);`  
Fastest:  
`_rotr(_byteswap_ulong(value), 8);`  
`_byteswap_ulong(_rotl(value, 8));`  
I also got rid of the unnecessary `memcpy`s.
For me this saves 50-100ms for large files.

optimize RGBA to BGRA conversion

---

src/JPEGView/MainDlg.cpp
src/JPEGView/MainDlg.h

For animated images, JPEGView currently sets a timer to wait for the next frame based on each frame's frametime. This doesn't account for the time we spend processing each frame, so the image ends up playing slower than it does in a browser or video player. To fix this, we calculate an offset based on the difference between each frametime and the actual time that the frame took to render. This isn't a perfect solution, but animated images should no longer be noticeably slower than in a browser.

Make animation frametimes appear closer to their actual values

---

src/JPEGView/MainDlg.cpp

JPEGView shows the acquisition date in the window title if it's found in the EXIF data, but not if it's found in the RAW metadata.  
Example files: https://github.com/lclevy/canon_cr3/issues/30#issuecomment-1586193932

Show acquisition date from RAW metadata in window title

---

src/JPEGView/ImageLoadThread.cpp

It's currently possible for AVIF files to be mistaken as HEIF when we read the file header. Major brands starting with "m" do not specify the encoding of the file, but we currently assume they're HEIFs. This means that animated AVIF files which use "msf1" as the major brand will be decoded with libheif, which doesn't support animation, and therefore either not render or appear static ([example](https://github.com/sylikc/jpegview/files/13343462/msf1.zip)). This also means that AVIF files without the major brand "avif" or "avis" will fail to be decoded if the user has the libavif and dav1d DLLs but not libheif.
Since we already use libheif as a fallback for libavif, we should just treat HEIF/AVIF files as AVIF if we can't determine their encoding from the header.
See …

Fix AVIF detection

---

src/JPEGView/EXIFReader.cpp

EXIF orientation should be ignored according to JXL and HEIF specs.  
Sources:  
[libjxl](https://github.com/libjxl/libjxl/blob/4451ce9fdd3780cc0ad5cf1fea529615a6d84f2d/doc/format_overview.md?plain=1#L62-L67)  
https://github.com/strukturag/libheif/issues/227#issuecomment-916176774  
https://github.com/AOMediaCodec/libavif/issues/996#issuecomment-1196157817  
https://zpl.fi/exif-orientation-in-different-formats/  
While testing this I found 2 issues:  
1. We don't support mirroring with the Orientation tag (see [0x112](https://exiftool.org/TagNames/EXIF.html)). [Relevant code](https://github.com/sylikc/jpegview/blob/57ac9bcf1b9154bc6650434a576d3fb85209d75f/src/JPEGView/JPEGImage.cpp#L1422-L1435)
2. libheif automatically rotates images based on the `irot` and `imir` boxes, but libavif …

Ignore EXIF orientation for HEIF/AVIF

---

src/JPEGView/PSDWrapper.cpp

The current way we skip image resource names is wrong, idk what I was thinking when I wrote it. Most PSDs don't store the names (they just use `00 00` as the string), which is why I didn't notice this before.
https://stackoverflow.com/questions/28519732/what-is-a-pascal-style-string

psd: properly skip image resource names

---

src/JPEGView/Helpers.cpp
src/JPEGView/ImageLoadThread.cpp

#261 broke CR3 detection. CR3 uses the HEIF container, so it gets detected as a HEIF before checking the file extension.
I added a check for the "crx " major brand and moved the unspecified encoding fallback after the file extension check. I moved TIFF detection here as well, which currently won't really do anything since it just goes to GDI+ anyway. I also added the `.HIF` extension used by newer Canon cameras (https://github.com/lclevy/canon_cr3/blob/master/heif.md)

Fix CR3 detection

---

src/JPEGView/JPEGLosslessTransform.cpp
src/JPEGView/SaveImage.cpp
src/JPEGView/TJPEGWrapper.cpp
src/JPEGView/TJPEGWrapper.h

Fix EXIF data being lost on lossless JPEG transformations

---

src/JPEGView/AVIFWrapper.cpp
src/JPEGView/BasicProcessing.cpp
src/JPEGView/BasicProcessing.h
src/JPEGView/JPEGImage.cpp

HEIF files can contain `clap`, `irot` and `imir` boxes which indicate cropping, rotation and mirroring transformations respectively. libheif takes care of this for us, but libavif doesn't. Fortunately we can just use existing helper functions to do the transformations.
Test files:  
https://github.com/AOMediaCodec/av1-avif/tree/master/testFiles/Link-U *
https://git.zpl.fi/exif-orientation/tree/images (RotXMirY.avif files)  
https://github.com/chromium/chromium/tree/main/third_party/blink/web_tests/images/resources/avif (cropped images)  
\* Note that the cropped AVIFs here fail to decode with libavif due to the crop's non-integer Y offset. They then fall back to libheif, so they can't be used for testing this change. Chromium disables libavif's strict `clap` validation and just ignores …

Implement AVIF transformations

---

src/JPEGView/ImageLoadThread.cpp
src/JPEGView/PNGWrapper.cpp
src/JPEGView/PNGWrapper.h

Adds support for EXIF data in non-animated PNGs when `ForceGDIPlus` or `UseEmbeddedColorProfiles` is true. This is similar to what we do for JPEGs.
Example: [paris_icc_exif_xmp_at_end.png](https://github.com/sylikc/jpegview/assets/93988953/4516308a-dbfd-467f-b89b-8f4ac7682374)

Support EXIF data in PNGs when using GDI+

---

src/JPEGView/ImageLoadThread.cpp
src/JPEGView/RAWWrapper.cpp

RawProcessor might not have an accurate number of colors before the RAW image is unpacked and processed. For the sample images we currently detect 4 colors instead of 3, so the decoded image looks corrupt. The `unpack` method already has [size checks similar to ours](https://github.com/LibRaw/LibRaw/blob/0.21.1/src/decoders/unpack.cpp#L52-L77), so memory shouldn't be an issue if we get the info after processing.
K25 images use [PPM](https://en.wikipedia.org/wiki/Netpbm#Description) thumbnails, so `RawReader::ReadImage` can't parse them. If `DisplayFullsizeRaw=2` then we will show the full image, even though dcraw_mod would be able to get thumbnail. I changed this so we try dcraw before getting the fullsize.
Samples: https://sembiance.com/fileFormatSamples/image/kodakK25/

Fix decoding K25 raw images

---

src/JPEGView/PSDWrapper.cpp

Some PSDs rely on [the byte counts for each scan line](https://www.adobe.com/devnet-apps/photoshop/fileformatashtml/#50577409_pgfId-1054855) to be decoded correctly. ImageMagick seems to add a pad byte to each row in some cases when exporting to PSD. [Example](https://github.com/user-attachments/files/15812447/psd.scan.line.bytes.imagemagick.zip)
Also, "Desktop2.psd" from https://github.com/ImageMagick/ImageMagick/issues/1962 overshoots by 4 bytes on row 520 of the red plane. It fails to decode unless we use the byte counts.

psd: use byte counts for scan lines

---

src/JPEGView/XMMImage.cpp

`nFirstY`, `nSrcLineWidthPadded`, `nFirstX` and `nChannels` are type `int`; multiplying them, the result will internally be treated as `int` values again. For very large images, this can cause integer overflows, with the resulting negative values causing a wrong address in the `pSrc` pointer, leading to a crash. One possible fix is to cast those values to int64 (long long) before multiplication, as in the current PR does.
(Strictly speaking, this fix is not neccessary for `nFirstX*nChannels`, since that ones' product can't grow that large, with `nChannels` being a single digit value...)
Alternatively, we could get away with just using `uint32` instead of `long long`, since none of the factors should ever be negative. It would allow for images up to 65535x65535 in size not triggering on …

Fix possible crash on displaying very large images
